stages:
- check
- build

pre-commit:
  stage: check
  image: python:3
  before_script:
  - pip install "virtualenv<v20.24.6"  # temporary fix for gitlint
  - pip install "pre-commit==3.6.0"
  script:
  - TMP_MSG_FILE="$(mktemp)"
  - git log -1 --pretty=%B > "${TMP_MSG_FILE}"
  - pre-commit run
      --all-files
      --color=always
      --show-diff-on-failure
      --hook-stage commit &&
    pre-commit run
      --all-files
      --color=always
      --show-diff-on-failure
      --hook-stage commit-msg
      --commit-msg-filename "${TMP_MSG_FILE}" ||
    {
      >&2 echo "pre-commit checks failed. Please consider installing pre-commit";
      >&2 echo "hooks in your local Git clone by running \`make git-hooks-install\`.";
      exit 1;
    }

build-image:
  stage: build
  image: docker:stable
  script:
  - docker login -u gitlab-ci-token -p "${CI_JOB_TOKEN}" "${CI_REGISTRY}"
  - docker build -t "${CI_REGISTRY_IMAGE}/mail_relay:latest" .
  - docker push "${CI_REGISTRY_IMAGE}/mail_relay:latest"
  only:
  - master@Scientific-IT-Systems/administration/mail_relay
