FROM python:3.12-alpine
LABEL maintainer="Ingo Meyer <i.meyer@fz-juelich.de>"

ENV MAILPROXY_THIS_PORT "25"
ENV MAILPROXY_THIS_ENCRYPTION "NONE"
ENV MAILPROXY_THIS_USERNAME ""
ENV MAILPROXY_THIS_PASSWORD ""
ENV MAILPROXY_THIS_TLS_KEY_FILEPATH ""
ENV MAILPROXY_THIS_TLS_CERT_FILEPATH ""

ENV MAILPROXY_DEST_SERVER_NAME ""
ENV MAILPROXY_DEST_PORT "25"
ENV MAILPROXY_DEST_ENCRYPTION "NONE"
ENV MAILPROXY_DEST_USERNAME ""
ENV MAILPROXY_DEST_PASSWORD ""


WORKDIR /root/mail_relay
COPY . .

RUN pip install -r requirements.txt

EXPOSE 25
EXPOSE 465
EXPOSE 587

ENTRYPOINT ["python3"]
CMD ["mail_relay.py"]
